version: 2
jobs:
  build:
    docker:
      - image: circleci/golang

    working_directory: /go/src/github.com/elimity-com/scim
    environment:
      TEST_RESULTS_DIR: /tmp/test-results/go-test

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR
      - run: go get github.com/jstemmer/go-junit-report
      - run: go test -v | go-junit-report > ${TEST_RESULTS_DIR}/results.xml
      - store_artifacts:
          path: /tmp/test-results

      - store_test_results:
          path: /tmp/test-results
